apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: front
          image: gcr.io/nomadic-mesh-272815/nonogram/front
          ports:
            - containerPort: 80
