apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    tier: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: front-ingress
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: front
    servicePort: 8080
