plugins:
    - serverless-offline
    - serverless-plugin-typescript-express

service: nonogram-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-3

functions:
  http:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}