service: nonogram-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-3

package:
  exclude:
    - "**/*.ts"
    - "test/**"
    - "scripts/**"
    - ".vscode/**"
    - "*"

functions:
  http:
    handler: src/lambda.http
    timeout: 2
    events:
      - http: ANY /
      - http: ANY /{proxy+}
