# serverless.yml

service: nonogram-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-3

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'